In [4]:
import numpy as np 

In [6]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [11]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [19]:
ev = np.arange(10,51)
ev_boo = ev%2 < 1
print(ev[ev_boo])

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [25]:
mat = np.arange(0,9)
mat.reshape(3,3)



array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
np.random.rand(1)

array([0.17522694])

In [27]:
np.random.normal(0,1,25)

array([-0.77833368,  0.49051443, -0.29372259, -1.03483584,  0.62492067,
        1.83000334, -1.28571487,  0.42107606,  0.95958327,  0.61337959,
        1.82689424,  0.85174326,  0.59273384, -0.93624543, -1.83973658,
       -0.3740041 ,  0.42231344,  1.49869441,  0.83254571,  0.87472219,
        0.44085186, -0.59839672, -1.39163176, -0.75229443, -0.35355551])

In [39]:
L = np.arange(0.01,1.01,0.01)
L.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [40]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# HERE IS THE GIVEN MATRIX CALLED MAT
# USE IT FOR THE FOLLOWING TASKS
mat = np.arange(1,26).reshape(5,5)

# mat[2:,1:]
# mat[3,4]
# mat[:3,1:2]
# mat[-1,:]
# mat[3:,:]

array([[ 2],
       [ 7],
       [12]])

In [55]:
mat = np.arange(1,26).reshape(5,5)

int(np.sum(mat))

325

In [57]:
mat = np.arange(1,26).reshape(5,5)
standard_deviation = np.std(mat)
float(standard_deviation)

7.211102550927978

In [66]:
mat = np.arange(1,26).reshape(5,5)
np.sum(mat, axis = 0)

array([55, 60, 65, 70, 75])

In [ ]:
np.random.seed(45) # le chiffre en argumant n'a aucune importance (c'est un peu l'identifiant de la chaine aléatoire)
np.random.rand(10)

array([0.96455108, 0.50000836, 0.88952006, 0.34161365, 0.56714413,
       0.42754596, 0.43674726, 0.77655918, 0.53560417, 0.95374223])